profiles:
  default:
    data:
      host: https://api.weather.gov
      office: BOX
      position: 71,90

requests:
  weather_hourly: !request
    url: "{{host}}/gridpoints/{{office}}/{{position}}/forecast/hourly"
    method: GET

  weather_12hr: !request
    url: "{{host}}/gridpoints/{{office}}/{{position}}/forecast"
    method: GET
