profiles:
  default:
    data:
      weather_host: https://api.weather.gov
      office: BOX
      position: 71,90

requests:
  weather:
    requests:
      weather_hourly:
        method: GET
        url: '{{ weather_host }}/gridpoints/{{ office }}/{{ position }}/forecast/hourly'
      weather_12hr:
        method: GET
        url: '{{ weather_host }}/gridpoints/{{ office }}/{{ position }}/forecast'
