[package]
description = "Control system for a Raspberry Pi with e-ink display"
edition = "2021"
name = "goldfinger"
version = "0.1.0"

[dependencies]
anyhow = "1.0.72"
chrono = {version = "0.4.31", default-features = false, features = ["clock", "serde"]}
ctrlc = "3.4.4"
embedded-graphics = "0.6.2"
embedded-hal = {version = "0.2.3", features = ["unproven"]}
env_logger = "0.10.1"
linux-embedded-hal = "0.3.0"
log = "0.4.20"
serde = {version = "1.0.195", features = ["derive"]}
serde_json = {version = "1.0.111", default-features = false}
ssd1680 = "0.1.0"
ureq = {version = "2.9.6", features = ["json"]}
