[package]
description = "API and control system for a Raspberry Pi with character LCD"
edition = "2021"
name = "goldfinger"
version = "0.1.0"

[dependencies]
anyhow = "1.0.72"
chrono = {version = "0.4.31", default-features = false, features = ["clock"]}
env_logger = "0.10.1"
log = "0.4.20"
rocket = {version = "0.5.0", features = ["json"]}
rocket_dyn_templates = {version = "0.1.0", default-features = false, features = ["tera"]}
serde = {version = "1.0.195", features = ["derive"]}
serde_json = {version = "1.0.111", default-features = false}
serialport = {version = "4.3.0", default-features = false}
tokio = {version = "1.35.1", default-features = false, features = ["full"]}
